# Generated by Django 5.1.6 on 2025-03-10 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_scheduledpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpost',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='scheduled_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 7, 2, 27, 438053, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
